### ISSUE TITLE
system-contracts submodule points to commit e96dfe0 but it does not exist

### ISSUE THREAD

**Issue by charles-cooper** [matter-labs/era-compiler-tester#3]
per title -- the submodule here points to https://github.com/matter-labs/era-system-contracts/tree/e96dfe0b5093fa95c2fb340c0411c646327db921 but it's a non-existent commit

**Comment by hedgar2017** [comment]
> per title -- the submodule here points to https://github.com/matter-labs/era-system-contracts/tree/e96dfe0b5093fa95c2fb340c0411c646327db921 but it's a non-existent commit

Could you update it locally?
There are some open-sourcing efforts going on so the history must have been tweaked.

**Comment by charles-cooper** [comment]
No, because we are using it in CI

**Comment by charles-cooper** [comment]
for instance: https://github.com/vyperlang/vyper/actions/runs/6099550216/job/16552424324?pr=3415

**Comment by hedgar2017** [comment]
@charles-cooper done! Please check.

**Comment by charles-cooper** [comment]
seems to work, thanks! https://github.com/vyperlang/vyper/actions/runs/6099550216/job/16654938549
